config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "users/registrations"}

  root 'profile#index'

  get 'coles'                       => 'profile#coles', as: :coles

  post 'coles'                      => 'profile#colesUpdate', as: :coles_update

  get "coles_list"                  => 'cole#coles_list', as: :coles_list

  get "coles_list/:list/products"   => 'cole#coles_list_product', as: :coles_list_product

  get "coles_order"                 => 'cole#coles_order', as: :coles_order

  get "coles_order/:order/products" => 'cole#coles_order_product', as: :coles_order_product

  get "get_coles_details"           => 'cole#get_coles_order_products', as: :getColesOrderProducts

  post "add-products-to-cart"           => 'cole#add_products_to_cart', as: :add_products_to_cart
end

app/views/layouts/_footer.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 spaced spaced-bottom"></div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="header">

	<nav class="navbar navbar-default mega-menu">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".bs-navbar-collapse" aria-expanded="false" style="margin: 13px;">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="javascript:void(0);">
	      	<span>ShopJam</span>
	      </a>
	    </div>

	    <div class="collapse navbar-collapse bs-navbar-collapse" style="background:#fff;">
		  <ul class="nav navbar-nav navbar-right">
		    <% if user_signed_in? %>
		    	<li>
		    		<%= link_to('My Account', edit_user_registration_path) %>
		    	</li>
		    	<li>
		    		<a href="<%= coles_path %>">Coles Account</a>
		    	</li>
		    	<li>
		    		<a href="<%= coles_list_path %>">Coles Lists</a>
		    	</li>
		    	<li>
		    		<a href="<%= coles_order_path %>">Coles Orders</a>
		    	</li>
				<li>
					<%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "header_btn") %>
				</li>
		    <% else %>
		    	<li>
		    		<a href="/users/sign_in" class="header_btn">Log in</a>
		    	</li>
		    	<li>
		    		<a href="/users/sign_up" class="header_btn">Register</a>
		    	</li>
		    <% end %>
		  </ul>
		</div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    	<%= csrf_meta_tags %>
    	<title>ShopJam</title>
    	<%# Add All Stylesheets here %>
	    <%= stylesheet_link_tag  "application", media: "all", cache: true %>
	    <%# Add all Javascripts here %>
	    <%= javascript_include_tag "application", cache: true %>
	</head>
	<body class="open-sans">
		<%# Include header contains main menu %>
    	<%= render "layouts/header" %>

			<% unless flash.blank? %>
			  <div class="container-fluid">
			    <div class="row">
			      <div class="col-sm-10 col-xs-12 col-centered">
							<% flash.each do |key, value| %>
							  <div class="alert flash-<%= key %>">
									<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
									<%= value.to_s.html_safe %>
								</div>
							<% end %>
			      </div>
			    </div>
			  </div>
			<% end %>

		<%= yield %>

		<%= render "layouts/footer" %>
	</body>
</html>